# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
np.full(7, 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
np.arange(10, 100, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
tmp = np.random.random_sample(4)
print (tmp)
np.flip(tmp)

[0.28859403 0.49993692 0.55538017 0.80830687]


array([0.80830687, 0.55538017, 0.49993692, 0.28859403])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
tmp = np.diag([1, 2, 3, 4])
tmp[tmp == 0] = 7
tmp

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
(np.arange(25)%5).reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
tmp = np.random.random_sample((10,10))
print(tmp)
tmp - tmp.mean(axis = 1, keepdims=True)

[[0.41413486 0.42204594 0.71550086 0.4017111  0.34453203 0.26326084
  0.47695829 0.93987854 0.4516424  0.82931979]
 [0.36987329 0.50560024 0.07706643 0.45144039 0.56327573 0.46493685
  0.85034159 0.56509777 0.72588247 0.89541662]
 [0.17188992 0.78901479 0.83222463 0.65697871 0.73309697 0.46351498
  0.72395747 0.2574114  0.73808264 0.21571943]
 [0.57709651 0.37599073 0.41961473 0.0576037  0.44696469 0.88228202
  0.96078381 0.18121806 0.10114138 0.88430549]
 [0.94971157 0.33557406 0.22527067 0.69206219 0.14927726 0.60845916
  0.68659517 0.34969506 0.19187316 0.99262183]
 [0.20584144 0.65880694 0.89726391 0.39995615 0.41822981 0.97134287
  0.66560754 0.44231233 0.9041894  0.88016357]
 [0.02151484 0.53343545 0.46174406 0.58615375 0.13926399 0.39872184
  0.50479421 0.3152588  0.54700956 0.45600681]
 [0.12160647 0.30256362 0.6096233  0.00563299 0.99495257 0.88237729
  0.0842604  0.3996502  0.53842563 0.33921256]
 [0.69826148 0.94027984 0.52644063 0.9562967  0.14382649 0.87143317
  0.564753  

array([[-0.11176361, -0.10385252,  0.1896024 , -0.12418736, -0.18136644,
        -0.26263762, -0.04894018,  0.41398007, -0.07425607,  0.30342133],
       [-0.17701985, -0.0412929 , -0.46982671, -0.09545274,  0.01638259,
        -0.08195629,  0.30344846,  0.01820463,  0.17898933,  0.34852348],
       [-0.38629918,  0.2308257 ,  0.27403554,  0.09878961,  0.17490788,
        -0.09467412,  0.16576837, -0.3007777 ,  0.17989355, -0.34246966],
       [ 0.0883964 , -0.11270938, -0.06908538, -0.43109642, -0.04173543,
         0.39358191,  0.4720837 , -0.30748205, -0.38755873,  0.39560538],
       [ 0.43159756, -0.18253995, -0.29284334,  0.17394818, -0.36883675,
         0.09034514,  0.16848116, -0.16841896, -0.32624085,  0.47450781],
       [-0.43852996,  0.01443554,  0.25289251, -0.24441525, -0.22614159,
         0.32697147,  0.02123615, -0.20205906,  0.25981801,  0.23579217],
       [-0.37487549,  0.13704512,  0.06535373,  0.18976342, -0.25712634,
         0.00233151,  0.10840388, -0.08113153

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [7]:
tmp = np.random.random_sample((10,10))
print(tmp)
tmp - np.median(tmp, axis = 0, keepdims=True)

[[0.90986133 0.38713915 0.94534472 0.80337328 0.4928813  0.56190695
  0.65829272 0.10528103 0.18892601 0.9974321 ]
 [0.03997452 0.64634908 0.2971851  0.9173699  0.61595583 0.49668286
  0.46125015 0.9049532  0.97893743 0.88687656]
 [0.73188894 0.62001252 0.46616312 0.02733129 0.59630568 0.48319117
  0.05265975 0.85540117 0.76509618 0.59888107]
 [0.77919059 0.19628406 0.43949927 0.25076616 0.63835182 0.63216585
  0.37034995 0.30659297 0.12971323 0.06534345]
 [0.14817773 0.36039558 0.77751143 0.23081741 0.54286806 0.67685964
  0.10089884 0.31729272 0.46480029 0.127802  ]
 [0.21173436 0.40453598 0.38659118 0.0564134  0.78864644 0.84075508
  0.10208473 0.92126409 0.80890298 0.61289633]
 [0.04463296 0.50133064 0.49505664 0.15867445 0.92848551 0.74848426
  0.78576013 0.43949693 0.39612134 0.2638828 ]
 [0.30739268 0.21509998 0.8257533  0.43346781 0.95184688 0.61927368
  0.14288409 0.87621017 0.54934363 0.71003616]
 [0.22205187 0.28074164 0.54011408 0.19871701 0.74767389 0.36859407
  0.49775254

array([[ 0.64513905, -0.00869841,  0.46473484,  0.58860608, -0.13427252,
        -0.06381281,  0.3483921 , -0.32720493, -0.38952038,  0.56605017],
       [-0.22474775,  0.25051152, -0.18342478,  0.70260269, -0.01119799,
        -0.12903691,  0.15134953,  0.47246723,  0.40049104,  0.45549463],
       [ 0.46716667,  0.22417496, -0.01444676, -0.18743591, -0.03084815,
        -0.1425286 , -0.25724087,  0.42291521,  0.1866498 ,  0.16749914],
       [ 0.51446831, -0.1995535 , -0.04111061,  0.03599896,  0.01119799,
         0.00644609,  0.06044933, -0.12589299, -0.44873315, -0.36603849],
       [-0.11654454, -0.03544198,  0.29690155,  0.0160502 , -0.08428576,
         0.05113987, -0.20900178, -0.11519325, -0.1136461 , -0.30357993],
       [-0.05298792,  0.00869841, -0.0940187 , -0.15835381,  0.16149262,
         0.21503531, -0.20781588,  0.48877813,  0.23045659,  0.1815144 ],
       [-0.22008932,  0.10549307,  0.01444676, -0.05609275,  0.30133169,
         0.12276449,  0.47585952,  0.00701096

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
tmp = np.random.random_sample((5,5))
max = tmp.max(axis =1,keepdims=True)
min = tmp.min(axis =1,keepdims=True)
np.concatenate((tmp, max, min),axis = 1)

array([[0.73671617, 0.96627926, 0.87315719, 0.36284621, 0.07749112,
        0.96627926, 0.07749112],
       [0.92083415, 0.8977204 , 0.5094441 , 0.92295278, 0.30268382,
        0.92295278, 0.30268382],
       [0.303674  , 0.13138637, 0.1121758 , 0.50813674, 0.24573485,
        0.50813674, 0.1121758 ],
       [0.07373062, 0.37702277, 0.66795718, 0.08805733, 0.6507248 ,
        0.66795718, 0.07373062],
       [0.02110791, 0.37787957, 0.81739146, 0.22065854, 0.44217726,
        0.81739146, 0.02110791]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
tmp1 =np.mat(np.arange(0,51)[1::2]).reshape(5,5)
print(tmp1)
tmp2 =np.mat(np.arange(0,51)[2::2]).reshape(5,5)
print(tmp2)
tmp3 = tmp1@tmp2
print(tmp3)
np.linalg.inv(tmp3) # обратной матрицы не существует

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
[[ 750  800  850  900  950]
 [1850 2000 2150 2300 2450]
 [2950 3200 3450 3700 3950]
 [4050 4400 4750 5100 5450]
 [5150 5600 6050 6500 6950]]


LinAlgError: Singular matrix

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
tmp = np.zeros((8,8), dtype=int)
tmp[1::2,::2] = 1
tmp[::2,1::2] = 1
tmp

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])